[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules','lib']
fs_permissions = [{ access = "read", path = "./"}]
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@kyber.network/=node_modules/@kyber.network/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    '@root/=contracts/'
]

optimizer_runs = 200
verbosity = 3
fuzz_runs = 2048

[fmt]
tab_width = 2
number_underscore = "thousands"
quote_style = "single"

[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
goerli = "https://eth-goerli.public.blastapi.io"
sepolia = "https://eth-sepolia.public.blastapi.io"
polygon = "https://polygon.kyberengineering.io"
bsc = "https://bsc.kyberengineering.io"
arb = "https://rpc.ankr.com/arbitrum"
op = "https://optimism.meowrpc.com"
avax = "https://avax.meowrpc.com"
lineamain = "https://linea-mainnet.infura.io/v3/474d88f0f3bc480b900b6b7a630855b6"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
goerli = { key = "${ETHERSCAN_KEY}" }
polygon = { key = "${POLYGONSCAN_KEY}" }
bsc = { key = "${BSC_SCAN}" }
arb = { key = "${ARB_SCAN}" }
op = { key = "${OP_SCAN}" }
avax = { key = "${AVAX_SCAN}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
